<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Sumbang &middot; booKesma</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Icon -->
	<link rel="icon" type="icon/image" href="<?=$this->url->getBaseUri()?>/img/jpgpng/favicon.png">
	<link rel="stylesheet" type="text/css" href="<?=$this->url->getBaseUri()?>/vendor/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="<?=$this->url->getBaseUri()?>/font/font-awesome-4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="<?=$this->url->getBaseUri()?>/font/Linearicons-Free-v1.0.0/icon-font.min.css">
	<!-- adding bootstrap css-->
	<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/bootstrap.css" />
    <!-- adding bootstrap theme css-->
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/bootstrap-theme.css" />
    <!-- external page css -->
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/show.css" />
	<link rel="stylesheet" type="text/css" href="<?=$this->url->getBaseUri()?>/css/util.css">
	<link rel="stylesheet" type="text/css" href="<?=$this->url->getBaseUri()?>/css/main.css">
</head>
<body style="background-image:url('<?=$this->url->getBaseUri()?>/img/svg/bg_layer1.svg')">
	<div class="topnav" id="top-nav" style="z-index: 99;">
        <a class="home" href="<?=$this->url->getBaseUri()?>">
            <img src="<?=$this->url->getBaseUri()?>/img/svg/logo.svg" alt="booKesma">
        </a>
        <a href="<?=$this->url->getBaseUri().'login'?>">Masuk</a>
        <a href="<?=$this->url->getBaseUri().'register'?>">Daftar</a>
        <a href="<?=$this->url->getBaseuri().'koleksi'?>">Koleksi</a>
        <a href="<?=$this->url->getBaseuri().'bagaimana'?>">Bagaimana</a>
        <a href="<?=$this->url->getBaseuri().'sumbang'?>">Sumbang</a>
        <a href="javascript:void(0);" class="icon" onclick="navbar()">
            <img src="<?=$this->url->getBaseUri()?>/img/svg/hamburger-menu.svg" alt="menu">
        </a>
    </div>
<br><br><br>
	<div class="container-contact100" >
		<div style="border:3px solid lightblue;" class="wrap-contact100">
			<div class="contact100-form-title" style="background-image: url('<?=$this->url->getBaseUri()?>/img/1.jpg');">
				<span class="contact100-form-title-1">
					FORM SUMBANG
				</span>
			</div>
			<?=$this->tag->form(['sumbang','method'=>'post','class'=>'contact100-form validate-form','enctype'=>"multipart/form-data"]);?>
			<!-- <form class="contact100-form validate-form"> -->

				<div class="wrap-input100 validate-input" data-validate="NRP is required">
					<span class="label-input100">NRP:</span>
					<?php echo $form->render('snrp'); ?>
					<!-- <input class="input100" type="text" name="nrp" placeholder="Masukkan NRP"> -->
					<span class="focus-input100"></span>
				</div>

				<div class="wrap-input100 validate-input" data-validate="Name is required">
					<span class="label-input100">Nama:</span>
					<?php echo $form->render('sname'); ?>
					<!-- <input class="input100" type="text" name="name" placeholder="Masukkan Nama"> -->
					<span class="focus-input100"></span>
				</div>

				<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
					<span class="label-input100">Email:</span>
					<?php echo $form->render('semail'); ?>
					<!-- <input class="input100" type="text" name="email" placeholder="Masukkan Email"> -->
					<span class="focus-input100"></span>
				</div>

				<div class="wrap-input100 validate-input" data-validate="No HP is required">
					<span class="label-input100">No HP:</span>
					<?php echo $form->render('snohp'); ?>
					<!-- <input class="input100" type="text" name="phone" placeholder="Masukkan Nomer HP"> -->
					<span class="focus-input100"></span>
				</div>
				<div class="wrap-input100 validate-input" data-validate="Departemen is required">
					<span class="label-input100">Departemen:</span>
					<?php echo $form->render('sdepartemen'); ?>
					<!-- <input class="input100" type="text" name="departemen" placeholder="Masukkan Departemen"> -->
					<span class="focus-input100"></span>
				</div>
				<div class="wrap-input100 validate-input" data-validate="Universitas is required">
					<span class="label-input100">Universitas:</span>
					<?php echo $form->render('suniversitas'); ?>
					<!-- <input class="input100" type="text" name="universitas" placeholder="Masukkan Universitas"> -->
					<span class="focus-input100"></span>
				</div>

				<div class="wrap-input100 validate-input" data-validate="Judul Buku is required">
					<span class="label-input100">Judul Buku:</span>
					<?php echo $form->render('sjudulbuku'); ?>
					<!-- <input class="input100" type="text" name="judul" placeholder="Masukkan Judul Buku"> -->
					<span class="focus-input100"></span>
				</div>

				<div class="wrap-input100 validate-input" data-validate="Tebal Halaman is required">
					<span class="label-input100">Tebal Halaman:</span>
					<?php echo $form->render('stebalhalaman'); ?>
					<!-- <input class="input100" type="text" name="halaman" placeholder="Masukkan Tebal Halaman"> -->
					<span class="focus-input100"></span>
				</div>

				<div class="wrap-input100 validate-input" data-validate = "Deskripsi Buku is required">
					<span class="label-input100">Deskripsi Buku:</span>
					<?php echo $form->render('sdeskripsibuku'); ?>
					<!-- <textarea class="input100" name="desk" placeholder="Deskripsi Buku ...."></textarea> -->
					<span class="focus-input100"></span>
				</div>

				<div class="wrap-input100 validate-input" data-validate="Gambar Buku is required">
					<span class="label-input100">Gambar Buku:</span>
					<?php echo $form->render('sgambar'); ?>
					<!-- <input class="input100" type="file" name="halaman"> -->
					<span class="focus-input100"></span>
				</div>

				<div class="wrap-input100 validate-input" data-validate="Tanggal mengumpulkan is required">
					<span class="label-input100">Tanggal Mengumpulkan Buku:</span>
					<?php echo $form->render('tanggal'); ?>
					<!-- <input class="input100" type="date" name="tanggal_bertemu" placeholder="Masukkan Tanggal Kembali"> -->
					<span class="focus-input100"></span>
                </div>

				<div class="container-contact100-form-btn">
					<?php echo $form->render('ssubmit'); ?>
					<!-- <button class="contact100-form-btn">
						<span>
							
							<i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
						</span>
					</button> -->
				</div>
			<?= $this->tag->endForm()?>
			<!-- </form> -->
		</div>
	</div>



	<div id="dropDownSelect1"></div>

	<script src="<?=$this->url->getBaseUri()?>/vendor/jquery/jquery-3.2.1.min.js"></script>
	<script src="<?=$this->url->getBaseUri()?>/vendor/bootstrap/js/popper.js"></script>
	<script src="<?=$this->url->getBaseUri()?>/vendor/bootstrap/js/bootstrap.min.js"></script>
	<script src="<?=$this->url->getBaseUri()?>/js/main.js"></script>

</body>
</html>
