<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Bagaimana? &middot; booKesma</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Icon -->
	<link rel="icon" type="icon/image" href="<?=$this->url->getBaseUri()?>/img/jpgpng/favicon.png">
    <!-- adding bootstrap css-->
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/bootstrap.css" />
    <!-- adding bootstrap theme css-->
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/bootstrap-theme.css" />
    <!-- external page css -->
  <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/how.css" />
  <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/stylesheet.css" />
  <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/yap.css" />
  <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/bootstrap.min.css" />

  <link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
</head>
<body style="background-image:url('<?=$this->url->getBaseUri()?>/img/svg/bg_layer2.svg'); font-family:mp;">
    <div class="topnav" id="top-nav">
        <a class="home" href="<?=$this->url->getBaseUri()?>">
            <img src="<?=$this->url->getBaseUri()?>/img/svg/logo.svg" alt="booKesma">
        </a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseUri().'login'?>">Masuk</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseUri().'register'?>">Daftar</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'koleksi'?>">Koleksi</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'bagaimana'?>">Bagaimana</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'sumbang'?>">Sumbang</a>
        <a style="text-decoration: none;" href="javascript:void(0);" class="icon" onclick="navbar()">
            <img src="<?=$this->url->getBaseUri()?>/img/svg/hamburger-menu.svg" alt="menu">
        </a>
	</div>
           <!-- Work Section -->
           <section id="work" class="work sections">
            <div class="container">
                <div class="row">
                    <div class="main_mix_content text-center">
                        <div class="head_title">
                            <h1>our best work</h1>
                        </div><!-- End of head title -->

                        <div id="mixcontent" class="mixcontent text-center">
                            <div class="col-sm-4 col-xs-12">
                                <div class="single_mixi_portfolio">
                                    <img src="<?=$this->url->getBaseUri()?>/img/pf01.jpg" alt="" />
                                    <div class="single_work_overlay">
                                        <h4>Rangga Kusuma Dinata</h4>
                                        <div class="separator"></div>
                                        <p>05111740000120</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4 col-xs-12">
                                <div class="single_mixi_portfolio">
                                    <img src="<?=$this->url->getBaseUri()?>/img/pf5.jpg" alt="" />
                                    <div class="single_work_overlay">
                                        <h4>Safhira Maharani</h4>
                                        <div class="separator"></div>
                                        <p>05111740000027</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4 col-xs-12">
                                <div class="single_mixi_portfolio">
                                    <img src="<?=$this->url->getBaseUri()?>/img/pf3.png" alt="" />
                                    <div class="single_work_overlay">
                                        <h4>I Nyoman Yoga Mahottama</h4>
                                        <div class="separator"></div>
                                        <p>05111740000159</p>
                                    </div>
                                </div>
                            </div>                 
                </div>
            </div>
        </section> 
<div class="container" style="background-color: #FAE3E9;">
  <!-- Trigger the modal with a button -->
  <div style="width:100%; display:inline-table; float:left;">
	<div style="width:70%; display: inline-table; float:left; padding:3%;">
		<button  style="background: url('https://www.bookabuku.com/file/frontend/images/how-thumbnail-subscribe.jpg') no-repeat; width:100%; height:450px;; background-position: center; background-size: cover; font-size: 30px;" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal" color="black">RESERVASI
		</button>
	</div>
	<div style="width:30%; float:left;padding: 3%;">
	<h3>Untuk Reservasi kalian bisa mengisi form untuk login terlebih dahulu. Setelah itu, kalian bisa memilih buku sesuai keinginan. Jika terdapat masalah dalam hal pengisian data. Harap hubungi KESMA HMTC.</h3>
	</div>
  </div>
</div>
<br><br>
<div class="container" style="background-color: #BFDAD5;">
  <!-- Trigger the modal with a button -->
  <div style="width:100%; display:inline-table; float:left;padding:3%;">
	<div style="width:30%; float:left; padding:3%;">
	<h3>Untuk Peminjaman kalian bisa mengisi form untuk login terlebih dahulu. Setelah itu, kalian bisa memilih buku sesuai keinginan. Silahkan ambil buku sesuai jadwal janjian dengan pengurus KESMA. Jika terdapat masalah dalam hal pengisian data. Harap hubungi KESMA HMTC.</h3>
	</div>
	<div style="width:70%; display: inline-table; float:left;">
		<button  style="background: url('https://www.bookabuku.com/file/frontend/images/how-thumbnail-borrow.jpg') no-repeat; width:100%; height:450px; background-position: center; background-size: cover; font-size: 30px; " class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal2" color="black">PEMINJAMAN
		</button>
	</div>
  </div>
</div>
<br><br>
<div class="container" style="background-color: #FAE3E9;">
  <!-- Trigger the modal with a button -->
  <div style="width:100%; display:inline-table; float:left;">
  <div style="width:70%; display: inline-table; float:left;padding:3%;">
		<button  style="background: url('https://www.bookabuku.com/file/frontend/images/how-thumbnail-lend.jpg') no-repeat; width:100%; height:450px; background-position: center; background-size: cover; font-size: 30px; " class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal3" color="black">PENYUMBANGAN
		</button>
	</div>
	<div style="width:30%; float:left; padding:3%;">
	<h3>Untuk Penyumbangan kalian bisa login terlebih dahulu. Setelah itu, kalian bisa mengisi form Penyumbangan dan mengisi jadwal janjian dengan pengurus KESMA. Jika terdapat masalah dalam hal pengisian data. Harap hubungi KESMA HMTC.</h3>
	</div>
  </div>
</div>
<br><br><br>

<!-- adding jquery -->
<script src="<?=$this->url->getBaseUri()?>/js/jquery-3.3.1.js"></script>
<!-- adding bootstrap -->
<script src="<?=$this->url->getBaseUri()?>/js/bootstrap.js"></script>
<!-- adding external script -->
<script src="<?=$this->url->getBaseUri()?>/js/show.js"></script>
</body>
</html>