<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page not found &middot; booKesma</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="css/show404.css" />
    <script src="show404.js"></script>
</head>
<body>
    <img src="img/svg/notfound.svg" alt="notfound">
    <p class="d">
    Maaf halaman yang kamu cari saat ini tidak ada.
    </p>
</body>
</html>