<!DOCTYPE html>
<html>
<head>
		<meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Masuk &middot; booKesma</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Icon -->
		<link rel="icon" type="icon/image" href="<?=$this->url->getBaseUri()?>/img/jpgpng/favicon.png">
    <!-- adding bootstrap css-->
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/bootstrap.css" />
    <!-- adding bootstrap theme css-->
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/bootstrap-theme.css" />
    <!-- external page css -->
		<link rel="stylesheet" type="text/css" href="<?=$this->url->getBaseUri()?>/css/show.css">
  	<link rel="stylesheet" type="text/css" href="<?=$this->url->getBaseUri()?>/css/masuk.css">
</head>
<body>
<div class="topnav" id="top-nav" style="z-index: 99;">
        <a class="home" href="<?=$this->url->getBaseUri()?>">
            <img src="<?=$this->url->getBaseUri()?>/img/svg/logo.svg" alt="booKesma">
        </a>
        <a href="<?=$this->url->getBaseUri().'login'?>">Masuk</a>
        <a href="<?=$this->url->getBaseUri().'register'?>">Daftar</a>
        <a href="<?=$this->url->getBaseuri().'koleksi'?>">Koleksi</a>
        <a href="<?=$this->url->getBaseuri().'bagaimana'?>">Bagaimana</a>
        <a href="<?=$this->url->getBaseuri().'sumbang'?>">Sumbang</a>
        <a href="javascript:void(0);" class="icon" onclick="navbar()">
            <img src="<?=$this->url->getBaseUri()?>/img/svg/hamburger-menu.svg" alt="menu">
        </a>
    </div>
	<div class="container">
		<h2>Masuk</h2>
		<?php echo $this->tag->form("login");?>
		<div class="form-group">
			<label>Email</label>
			<?php echo $form->render('remail'); ?>
		</div>
		<div class="form-group">
			<label title="Don't use the same password, we don't do alot in security">Password</label>
			<?php echo $form->render('rpassword'); ?>
		</div>
		<div class="form-group">
			<?php echo $form->render('rsubmit',['value'=>'Masuk']); ?>
		</div>
		<div>
		<p id="remind">
			Belum memiliki akun? <a href="<?=$this->url->getBaseUri().'register'?>">Daftar aja!</a>
		</p>
		</form>
	</div>
<!-- adding bootstrap -->
<script src="<?=$this->url->getBaseUri()?>/js/bootstrap.js"></script>
<!-- adding jquery -->
<script src="<?=$this->url->getBaseUri()?>/js/jquery-3.3.1.js"></script>
<!-- adding external script -->
</body>
</html>