<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Keluar &middot; booKesma</title>
    <!-- Icon -->
	<link rel="icon" type="icon/image" href="img/jpgpng/favicon.png">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- adding bootstrap css-->
    <link rel="stylesheet" type="text/css" media="screen" href="css/bootstrap.css" />
    <!-- adding bootstrap theme css-->
    <link rel="stylesheet" type="text/css" media="screen" href="css/bootstrap-theme.css" />
    <!-- external page css -->
    <link rel="stylesheet" type="text/css" media="screen" href="css/show404.css" />   
</head>
<body>
    <div class="container">
        <div class="content">
            <img style="width:25vw; height:25vw;" src="img/svg/logo_icon.svg" alt="logout">
            <div class="title">
                Terima kasih telah menggunakan layanan kami.
                <a style="color: #0a0e29" href="<?=$this->url->getBaseUri()?>">\nMampir-mampir lagi ya!</a>
            </div>
        </div>
    </div>
    <!-- adding jquery -->
    <script src="js/jquery-3.3.1.js"></script>
    <!-- adding bootstrap -->
    <script src="js/bootstrap.js"></script>
</body>
</html>