
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>booKesma &middot; Pinjam-Sumbang Buku Akademik Informatika ITS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Icon -->
	<link rel="icon" type="icon/image" href="img/jpgpng/favicon.png">
    <!-- adding bootstrap css-->
    <link rel="stylesheet" type="text/css" media="screen" href="css/bootstrap.css" />
    <!-- adding bootstrap theme css-->
    <link rel="stylesheet" type="text/css" media="screen" href="css/bootstrap-theme.css" />
    <!-- external page css -->
    <link rel="stylesheet" type="text/css" media="screen" href="css/show.css" />
</head>
<body style="background-image: url('img/svg/bg_layer1.svg')">
    <div class="topnav" id="top-nav">
        <a class="home" href="<?=$this->url->getBaseUri()?>">
            <img src="img/svg/logo.svg" alt="booKesma">
        </a>
        <a href="<?=$this->url->getBaseUri().'login'?>">Masuk</a>
        <a href="<?=$this->url->getBaseUri().'register'?>">Daftar</a>
        <a href="<?=$this->url->getBaseuri().'koleksi'?>">Koleksi</a>
        <a href="<?=$this->url->getBaseuri().'bagaimana'?>">Bagaimana</a>
        <a href="<?=$this->url->getBaseuri().'sumbang'?>">Sumbang</a>
        <a href="javascript:void(0);" class="icon" onclick="navbar()">
            <img src="img/svg/hamburger-menu.svg" alt="menu">
        </a>
    </div>
    <br><br><br><br>
<div class="container" style="background-color: lightblue; padding: 30px; border-radius:10%;">
  <div class="row">
    <div class="col-sm-7" style="font-family:mp; font-size: 20px;">
        <h2 style="font-size: 40px; background-color: #FAE3E9; padding: 3%; border-radius:5%;"><b>BUKU?</b></h2>
        <p style="padding:3%; text-alig;n:justify">Buku yang kubaca selalu memberi sayap-sayap baru.
Membawaku terbang ke taman-taman pengetahuan paling menawan, melintasi waktu dan peristiwa, berbagi cerita cinta, menyapa semua tokoh yang ingin kujumpai, sambil bermain di lengkung pelangi.</p>
    </div>
    <div class="col-sm-5">
        <img src="img/jpgpng/ambiz-introduction.jpg" style="width: 100%;">
    </div>
  </div>
</div>
<br><br>
<div class="container" style="background-color: lightgreen;padding: 30px; border-radius:10%;">
  <div class="row">
    <div class="col-sm-5">
        <img src="img/jpgpng/isi2.jpg" style="width: 100%;">
    </div>
    <div class="col-sm-7" style="font-family:mp; font-size: 20px;">
    <h2 style="font-size: 40px; background-color: #FAE3E9; padding: 3%; border-radius:5%;">MENGAPA BOOKESMA?</h2>
        <p style="padding:3%; text-alig;n:justify">Buku adalah jendela dunia, sebagai generasi muda haruslah kita mencintai buku</p>
    </div>
  </div>
</div>
<div id="header">
<div id="kategori">
    <h1>KATEGORI BUKU</h1>
    <div id="kolom">
        <img src="img/jpgpng/isi2.jpg" style="width: 100%;">
        <button>Semester 1</button>
    </div>
    <div id="kolom">
        <img src="img/jpgpng/isi2.jpg" style="width: 100%;">
        <button>Semester 2</button>
    </div>
    <div id="kolom">
        <img src="img/jpgpng/isi2.jpg" style="width: 100%;">
        <button>Semester 3</button>
    </div>
    <div id="kolom">
        <img src="img/jpgpng/isi2.jpg" style="width: 100%;">
        <button>Semester 4</button>
    </div>
    <div id="kolom">
        <img src="img/jpgpng/isi2.jpg" style="width: 100%;">
        <button>Semester 5</button>
    </div>
    <div id="kolom">
        <img src="img/jpgpng/isi2.jpg" style="width: 100%;">
        <button>Semester 6</button>
    </div>
</div>
<div id="bagaimana">
    <h1>BAGAIMANA ?</h1>
    <div id="kolombagaimana">
        <img src="img/jpgpng/isi2.jpg" style="width: 100%;">
        <button>Reservasi</button>
    </div>
    <div id="kolombagaimana">
        <img src="img/jpgpng/isi2.jpg" style="width: 100%;">
        <button>Peminjaman</button>
    </div>
    <div id="kolombagaimana">
        <img src="img/jpgpng/isi2.jpg" style="width: 100%;">
        <button>Penyumbangan</button>
    </div>
</div>
<div id="footer">
    <div id="kolomfooter">
    </div>
    <div id="kolomfooter">
        <h1>Our Media Social</h1>
        <a href="#"><img src="img/jpgpng/icon-facebook.png" style="width: 5%;"></a>
        <a href="#"><img src="img/jpgpng/icon-mail.png" style="width: 5%;"></a>
        <a href="#"><img src="img/jpgpng/icon-twitter.png" style="width: 5%;"></a>
        <br><br>
        <h3>Kategori Buku</h3>
        <h3>Bagaimana?</h3><br>
    </div>
    <div id="kolomfooter">
    </div>
</div>
<!-- adding bootstrap -->
<script src="js/bootstrap.js"></script>
<!-- adding jquery -->
<script src="js/jquery-3.3.1.js"></script>
<!-- adding external script -->
<script src="js/show.js"></script>
</body>
</html>