<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page not found &middot; booKesma</title>
    <!-- Icon -->
	<link rel="icon" type="icon/image" href="img/jpgpng/favicon.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- adding bootstrap css-->
    <link rel="stylesheet" type="text/css" media="screen" href="css/bootstrap.css" />
    <!-- adding bootstrap theme css-->
    <link rel="stylesheet" type="text/css" media="screen" href="css/bootstrap-theme.css" />
    <!-- external page css -->
    <link rel="stylesheet" type="text/css" media="screen" href="css/show404.css" />   
</head>
<body>
    <div class="container">
        <div class="content">
            <img src="img/svg/notfounded.svg" alt="notfound">
            <div class="title">
                Maaf halaman yang kamu cari saat ini tidak ada.
            </div>
        </div>
    </div>
    <!-- adding jquery -->
    <script src="js/jquery-3.3.1.js"></script>
    <!-- adding bootstrap -->
    <script src="js/bootstrap.js"></script>
</body>
</html>