<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Form Buku &middot; booKesma</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Icon -->
	  <link rel="icon" type="icon/image" href="<?=$this->url->getBaseUri()?>/img/jpgpng/favicon.png">
    <!-- adding bootstrap css-->
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/bootstrap.css" />
    <!-- adding bootstrap theme css-->
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/bootstrap-theme.css" />
    <!-- external page css -->
	<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/how.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/book.css" />
    <link href="https://fonts.googleapis.com/css?family=Oleo+Script:400,700" rel="stylesheet">
</head>
<body style="background-image:url('<?=$this->url->getBaseUri()?>/img/svg/bg_layer2.svg'); font-family:mp;">
<div class="topnav" id="top-nav" style="z-index: 99;">  
    <a class="home" href="<?=$this->url->getBaseUri()?>">
            <img src="<?=$this->url->getBaseUri()?>/img/svg/logo.svg" alt="booKesma">
        </a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'logout'?>">Keluar</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'user'?>">Riwayat</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseUri().'user/profile'?>">Hai, <?=$this->session->get('auth')['s_name'] ?>!</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'koleksi'?>">Koleksi</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'bagaimana'?>">Bagaimana</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'sumbang'?>">Sumbang</a>
        
        <?php
            $role = $this->session->get('auth')['s_role'];
            if ($role==="admin") {
        ?>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'admin'?>">Admin</a>
        <?php
            }
        ?>
        <a href="javascript:void(0);" class="icon" onclick="navbar()">
            <img src="<?=$this->url->getBaseUri()?>/img/svg/hamburger-menu.svg" alt="menu">
        </a>
</div>
	<br><br><br><br>
    <div class="container" style="backgroung-color:white; border: 3px solid darkblue; border-radius:10%;">
    <section id="contact" style="border-radius:10%;">
			<div class="section-content">
				<span class="content-header">Form Buku Admin</span>
			</div>
			<div class="contact-section">
			<div class="container">
				<?php echo $this->tag->form(["admin/buku",'method'=>'post','class'=>'contact100-form validate-form','enctype'=>"multipart/form-data"])?>
					<div class="col-md-6 form-line">
			  			<div class="form-group">
			  				<label>Judul Buku</label>
							<?php echo $form->render('bjudul')?>
				  		</div>
				  		<div class="form-group">
					    	<label>Jumlah Halaman</label>
					    	<?php echo $form->render('bjumhal')?>
					  	</div>	
					  	<div class="form-group">
					    	<label>Tersedia</label>
					    	<?php echo $form->render('btersedia')?>
			  			</div>
			  			<div class="form-group">
					    	<label>Semester</label>
					    	<?php echo $form->render('bsemester')?>
			  			</div>
			  		</div>
			  		<div class="col-md-6">
			  			<div class="form-group">
			  				<label for ="description">Deskripsi</label>
							  <?php echo $form->render('bdeskbuk')?>
			  			</div>
			  			<div class="form-group">
					    	<label>Gambar</label>
					    	<?php echo $form->render('bgambar')?>
			  			</div>
			  			<div class="form-group">
						  <a href="<?=$this->url->getBaseUri().'admin'?>" class="btn btn-default btn-md">Kembali</a>
							<?php echo $form->render('bsubmit')?>
			  			</div>
					</div>
					<?= $this->tag->endForm()?>
			</div>
		</section>
    </div>
 
<!-- adding jquery -->
<script src="<?=$this->url->getBaseUri()?>/js/jquery-3.3.1.js"></script>
<!-- adding bootstrap -->
<script src="<?=$this->url->getBaseUri()?>/js/bootstrap.js"></script>
<!-- adding external script -->
<script src="<?=$this->url->getBaseUri()?>/js/show.js"></script>
</body>
</html>