<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<br>
<div style="background-image:url('<?=$this->url->getBaseUri()?>/img/back.jpg'); font-family: mp; padding:5% 10% 5% 10%;margin:5%; background-size:cover;">
    <h1 style=" text-align: center;padding:5%; border-radius:10%;">
    <img src="<?=$this->url->getBaseUri()?>/img/svg/logo.svg" alt="booKesma">
    <b>BUKTI Pengembalian</b></h1>

	<h4>Judul Buku:</h4><br>
	<h4>Deskripsi Buku:</h4><br>
	<h4>Gambar Buku:</h4><br>	
    <h4>Tanggal Pengembalian:</h4><br>
    <h4>Tanggal Buku Kembali:</h4><br>
	<h3>Buku ini dipesan oleh: </h3>
	<h4>Nama: </h4><br>
    <h4>NRP: </h4><br>
    <h4>Ini adalah bukti kamu melakukan pengembalian, simpan baik-baik buktinya ya!</h4>
    <h4>Code: </h4>
</div>
</body>
</html>