<!DOCTYPE html>
<html>
<head>
	<title></title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Koleksi &middot; booKesma</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Icon -->
	<link rel="icon" type="icon/image" href="<?=$this->url->getBaseUri()?>/img/jpgpng/favicon.png">
    <!-- adding bootstrap css-->
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/bootstrap.css" />
    <!-- adding bootstrap theme css-->
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/bootstrap-theme.css" />
    <!-- external page css -->
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/show.css" />
</head>
<body>
<div class="topnav" id="top-nav" style="z-index: 99;">  
    <a class="home" href="<?=$this->url->getBaseUri()?>">
            <img src="<?=$this->url->getBaseUri()?>/img/svg/logo.svg" alt="booKesma">
        </a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'logout'?>">Keluar</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'user'?>">Riwayat</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseUri().'user/profile'?>">Hai, <?=$this->session->get('auth')['s_name'] ?>!</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'koleksi'?>">Koleksi</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'bagaimana'?>">Bagaimana</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'sumbang'?>">Sumbang</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'user/chat'?>">Chatting</a>
        <?php
            $role = $this->session->get('auth')['s_role'];
            if ($role==="admin") {
        ?>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'admin'?>">Admin</a>
        <?php
            }
        ?>
        <a href="javascript:void(0);" class="icon" onclick="navbar()">
            <img src="<?=$this->url->getBaseUri()?>/img/svg/hamburger-menu.svg" alt="menu">
        </a>
</div>
    <br><br><br><br>
<div class="container-fluid" style="background-color: ; padding:1%;">
    <h2 style="font-family: mp; font-size:45px; text-align:center; color:black;"><b>-KATEGORI BUKU-</b></h2>
</div>
<div class="container-fluid" style="background-color: white;padding: 30px; margin-left:10%;">
  <div class="row">
    <div class="col-sm-3" style="background-image: url('<?=$this->url->getBaseUri()?>/img/svg/bg_layer1.svg'); padding: 2%; border-radius:5%; margin:2%;" >
        <img src="<?=$this->url->getBaseUri()?>/img/svg/semester1.svg" style="width: 100%;">
        <br><br>
        <a href="<?=$this->url->getBaseUri().'user/koleksi/semester/1'?>" style="margin-left:30%;" type="button" class="btn btn-info btn-md">Semester 1</a>
    </div>
    <div class="col-sm-3" style="background-image: url('<?=$this->url->getBaseUri()?>/img/svg/bg_layer2.svg'); padding: 2%; border-radius:5%; margin:2%;">
        <img src="<?=$this->url->getBaseUri()?>/img/svg/semester2.svg" style="width: 100%;">
        <br><br>
        <a href="<?=$this->url->getBaseUri().'user/koleksi/semester/2'?>" style="margin-left:30%;" type="button" class="btn btn-info btn-md">Semester 2</a>
    </div>
    <div class="col-sm-3" style="background-image:url('<?=$this->url->getBaseUri()?>/img/svg/bg_layer3.svg'); padding: 2%; border-radius:5%; margin:2%;">
        <img src="<?=$this->url->getBaseUri()?>/img/svg/semester3.svg" style="width: 100%;">
        <br><br>
        <a href="<?=$this->url->getBaseUri().'user/koleksi/semester/3'?>" style="margin-left:30%;" type="button" class="btn btn-info btn-md">Semester 3</a>
    </div>
    <div class="col-sm-3" style="background-image:url('<?=$this->url->getBaseUri()?>/img/svg/bg_layer3.svg'); padding: 2%; border-radius:5%; margin:2%;">
        <img src="<?=$this->url->getBaseUri()?>/img/svg/semester4.svg" style="width: 100%;">
        <br><br>
        <a href="<?=$this->url->getBaseUri().'user/koleksi/semester/4'?>" style="margin-left:30%;" type="button" class="btn btn-info btn-md">Semester 4</a>
    </div>
    <div class="col-sm-3" style="background-image:url('<?=$this->url->getBaseUri()?>/img/svg/bg_layer1.svg'); padding: 2%; border-radius:5%; margin:2%;">
        <img src="<?=$this->url->getBaseUri()?>/img/svg/semester5.svg" style="width: 100%;">
        <br><br>
        <a href="<?=$this->url->getBaseUri().'user/koleksi/semester/5'?>" style="margin-left:30%;" type="button" class="btn btn-info btn-md">Semester 5</a>
    </div>
    <div class="col-sm-3" style="background-image:url('<?=$this->url->getBaseUri()?>/img/svg/bg_layer2.svg'); padding: 2%; border-radius:5%; margin:2%;">
        <img src="<?=$this->url->getBaseUri()?>/img/svg/semester6.svg" style="width: 100%;">
        <br><br>
        <a href="<?=$this->url->getBaseUri().'user/koleksi/semester/6'?>" style="margin-left:30%;" type="button" class="btn btn-info btn-md">Semester 6</a>
    </div>
  </div>
</div>
<div class="container-fluid" style="background-color: white;padding: 30px; margin-left:10%;">
  <div class="row">
    <div class="col-sm-3" style="background-image:url('<?=$this->url->getBaseUri()?>/img/svg/bg_layer2.svg'); padding: 2%; border-radius:5%; margin:2%;">
        <img src="<?=$this->url->getBaseUri()?>/img/svg/semester7.svg" style="width: 100%;">
        <br><br>
        <a href="<?=$this->url->getBaseUri().'user/koleksi/semester/7'?>" style="margin-left:30%;" type="button" class="btn btn-info btn-md">Semester 7</a>
    </div>
    <div class="col-sm-3" style="background-image:url('<?=$this->url->getBaseUri()?>/img/svg/bg_layer3.svg'); padding: 2%; border-radius:5%; margin:2%;">
        <img src="<?=$this->url->getBaseUri()?>/img/svg/semester8.svg" style="width: 100%;">
        <br><br>
        <a href="<?=$this->url->getBaseUri().'user/koleksi/semester/8'?>" style="margin-left:30%;" type="button" class="btn btn-info btn-md">Semester 8</a>
    </div>
  </div>
</div>
</body>
</html>