<!DOCTYPE html>
<html>
<head>
	<title></title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Kategori Buku &middot; booKesma</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Icon -->
	<link rel="icon" type="icon/image" href="/bookesma.com/img/jpgpng/favicon.png">
    <!-- adding bootstrap css-->
    <link rel="stylesheet" type="text/css" media="screen" href="/bookesma.com/css/bootstrap.css" />
    <!-- adding bootstrap theme css-->
    <link rel="stylesheet" type="text/css" media="screen" href="/bookesma.com/css/bootstrap-theme.css" />
    <!-- external page css -->
    <link rel="stylesheet" type="text/css" media="screen" href="/bookesma.com/css/stylekategori.css" />
</head>
<body>
<div class="topnav" id="top-nav" style="z-index: 99;">
        <a class="home" href="<?=$this->url->getBaseUri()?>">
            <img src="/bookesma.com/img/svg/logo.svg" alt="booKesma">
        </a>
        <a href="<?=$this->url->getBaseUri().'login'?>">Masuk</a>
        <a href="<?=$this->url->getBaseUri().'register'?>">Daftar</a>
        <a href="<?=$this->url->getBaseuri().'koleksi'?>">Koleksi</a>
        <a href="<?=$this->url->getBaseuri().'bagaimana'?>">Bagaimana</a>
        <a href="<?=$this->url->getBaseuri().'sumbang'?>">Sumbang</a>
        <a href="javascript:void(0);" class="icon" onclick="navbar()">
            <img src="/bookesma.com/img/svg/hamburger-menu.svg" alt="menu">
        </a>
</div>
    <br><br><br><br>
<div class="container-fluid" style="background-color: ; padding:1%;">
    <h2 style="font-family: mp; font-size:45px; text-align:center; color:black;"><b>-KATEGORI BUKU-</b></h2>
</div>
<div class="container-fluid" style="background-color: white;padding: 30px; margin-left:10%;">
  <div class="row">
    <div class="col-sm-3" style="background-image: url('/bookesma.com/img/svg/bg_layer1.svg'); padding: 2%; border-radius:5%; margin:2%;" >
        <img src="/bookesma.com/img/svg/semester1.svg" style="width: 100%;">
        <br><br>
        <button style="margin-left:30%;" type="button" class="btn btn-info btn-md">Semester 1</button>
    </div>
    <div class="col-sm-3" style="background-image: url('/bookesma.com/img/svg/bg_layer2.svg'); padding: 2%; border-radius:5%; margin:2%;">
        <img src="/bookesma.com/img/svg/semester2.svg" style="width: 100%;">
        <br><br>
        <button style="margin-left:30%;" type="button" class="btn btn-info btn-md">Semester 2</button>
    </div>
    <div class="col-sm-3" style="background-image:url('/bookesma.com/img/svg/bg_layer3.svg'); padding: 2%; border-radius:5%; margin:2%;">
        <img src="/bookesma.com/img/svg/semester3.svg" style="width: 100%;">
        <br><br>
        <button style="margin-left:30%;" type="button" class="btn btn-info btn-md">Semester 3</button>
    </div>
    <div class="col-sm-3" style="background-image:url('/bookesma.com/img/svg/bg_layer3.svg'); padding: 2%; border-radius:5%; margin:2%;">
        <img src="/bookesma.com/img/svg/semester4.svg" style="width: 100%;">
        <br><br>
        <button style="margin-left:30%;" type="button" class="btn btn-info btn-md">Semester 4</button>
    </div>
    <div class="col-sm-3" style="background-image:url('/bookesma.com/img/svg/bg_layer1.svg'); padding: 2%; border-radius:5%; margin:2%;">
        <img src="/bookesma.com/img/svg/semester5.svg" style="width: 100%;">
        <br><br>
        <button style="margin-left:30%;" type="button" class="btn btn-info btn-md">Semester 5</button>
    </div>
    <div class="col-sm-3" style="background-image:url('/bookesma.com/img/svg/bg_layer2.svg'); padding: 2%; border-radius:5%; margin:2%;">
        <img src="/bookesma.com/img/svg/semester6.svg" style="width: 100%;">
        <br><br>
        <button style="margin-left:30%;" type="button" class="btn btn-info btn-md">Semester 6</button>
    </div>
  </div>
</div>
<div class="container-fluid" style="background-color: white;padding: 30px; margin-left:10%;">
  <div class="row">
    <div class="col-sm-3" style="background-image:url('/bookesma.com/img/svg/bg_layer2.svg'); padding: 2%; border-radius:5%; margin:2%;">
        <img src="/bookesma.com/img/svg/semester7.svg" style="width: 100%;">
        <br><br>
        <button style="margin-left:30%;" type="button" class="btn btn-info btn-md">Semester 7</button>
    </div>
    <div class="col-sm-3" style="background-image:url('/bookesma.com/img/svg/bg_layer3.svg'); padding: 2%; border-radius:5%; margin:2%;">
        <img src="/bookesma.com/img/svg/semester8.svg" style="width: 100%;">
        <br><br>
        <button style="margin-left:30%;" type="button" class="btn btn-info btn-md">Semester 8</button>
    </div>
  </div>
</div>
</body>
</html>