<!-- generate dynamic base url -->
<?php
    use Phalcon\Mvc\Url;
    $url = new Url();
?>
<!DOCTYPE html>
<html>
<head>
	<title>KATEGORI BUKU</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>booKesma &middot; Pinjam-Sumbang Buku Akademik Informatika ITS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Icon -->
	<link rel="icon" type="icon/image" href="img/jpgpng/favicon.png">
    <!-- adding bootstrap css-->
    <link rel="stylesheet" type="text/css" media="screen" href="css/bootstrap.css" />
    <!-- adding bootstrap theme css-->
    <link rel="stylesheet" type="text/css" media="screen" href="css/bootstrap-theme.css" />
    <!-- external page css -->
    <link rel="stylesheet" type="text/css" media="screen" href="css/stylekategori.css" />
</head>
<body>
<div class="topnav" id="top-nav" style="z-index: 99;">
        <a class="home" href="<?=$this->url->getBaseUri()?>">
            <img src="img/svg/logo.svg" alt="booKesma">
        </a>
        <a href="<?=$this->url->getBaseUri().'login'?>">Masuk</a>
        <a href="<?=$this->url->getBaseUri().'register'?>">Daftar</a>
        <a href="<?=$this->url->getBaseuri().'koleksi'?>">Koleksi</a>
        <a href="<?=$this->url->getBaseuri().'bagaimana'?>">Bagaimana</a>
        <a href="<?=$this->url->getBaseuri().'sumbang'?>">Sumbang</a>
        <a href="javascript:void(0);" class="icon" onclick="navbar()">
            <img src="img/svg/hamburger-menu.svg" alt="menu">
        </a>
</div>
    <br><br><br><br>
<div class="container-fluid" style="background-color: #463af3; padding:1%;">
    <h2 style="font-family: mp; font-size:40px; text-align:center; color:white;"><b>-KATEGORI BUKU-</b></h2>
</div>
<div class="container-fluid" style="background-color: white;padding: 30px;">
  <div class="row">
    <div class="col-sm-3" style="background-color: #FBD4C5; padding: 2%;">
        <img src="img/svg/semester1.svg" style="width: 100%;">
        <br><br>
        <button style="margin-left:0%;" type="button" class="btn btn-info btn-md">Semester 1</button>
    </div>
    <div class="col-sm-3" style="background-color: #BFDAD5; padding: 2%;">
        <img src="img/svg/semester2.svg" style="width: 100%;">
    </div>
    <div class="col-sm-3" style="background-color: #FBD4C5; padding: 2%;">
        <img src="img/svg/semester3.svg" style="width: 100%;">
    </div>
    <div class="col-sm-3" style="background-color: #BFDAD5; padding: 2%;">
        <img src="img/svg/semester4.svg" style="width: 100%;">
    </div>
  </div>
</div>
<div class="container-fluid" style="background-color: white;padding: 30px;">
  <div class="row">
    <div class="col-sm-3" style="background-color: #BFDAD5; padding: 2%;">
        <img src="img/svg/semester5.svg" style="width: 100%;">
    </div>
    <div class="col-sm-3" style="background-color:#FBD4C5 ; padding: 2%;">
        <img src="img/svg/semester6.svg" style="width: 100%;">
    </div>
    <div class="col-sm-3" style="background-color:#BFDAD5 ; padding: 2%;">
        <img src="img/svg/semester7.svg" style="width: 100%;">
    </div>
    <div class="col-sm-3" style="background-color: #FBD4C5; padding: 2%;">
        <img src="img/svg/semester8.svg" style="width: 100%;">
    </div>
  </div>
</div>
</body>
</html>