<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Edit Data Anda &middot; booKesma</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Icon -->
	<link rel="icon" type="icon/image" href="<?=$this->url->getBaseUri()?>/img/jpgpng/favicon.png">
    <!-- adding bootstrap css-->
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/bootstrap.css" />
    <!-- adding bootstrap theme css-->
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/bootstrap-theme.css" />
    <!-- external page css -->
	<link rel="stylesheet" type="text/css" href="<?=$this->url->getBaseUri()?>/css/show.css">
	<link rel="stylesheet" type="text/css" href="<?=$this->url->getBaseUri()?>/css/daftar.css">
</head>
<body>
<div class="topnav" id="top-nav" style="z-index: 99;">  
    <a class="home" href="<?=$this->url->getBaseUri()?>">
            <img src="<?=$this->url->getBaseUri()?>/img/svg/logo.svg" alt="booKesma">
        </a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'logout'?>">Keluar</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'user'?>">Riwayat</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseUri().'user/profile'?>">Hai, <?=$this->session->get('auth')['s_name'] ?>!</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'koleksi'?>">Koleksi</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'bagaimana'?>">Bagaimana</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'sumbang'?>">Sumbang</a>
        
        <?php
            $role = $this->session->get('auth')['s_role'];
            if ($role==="admin") {
        ?>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'admin'?>">Admin</a>
        <?php
            }
        ?>
        <a href="javascript:void(0);" class="icon" onclick="navbar()">
            <img src="<?=$this->url->getBaseUri()?>/img/svg/hamburger-menu.svg" alt="menu">
        </a>
</div>
	<div class="container">
		<h2>Edit Data Anda</h2>
		<?php echo $this->tag->form("user/profile");?>
		<div class="form-group">
			<label>Username</label>
			<?php echo $form->render('rname',['value'=>$nama]); ?>
		</div>
		<div class="form-group">
			<label>NRP</label>
			<?php echo $form->render('rnrp',['value'=>$nrp]); ?>
		</div>
		<div class="form-group">
			<label>Email</label>
			<?php echo $form->render('remail',['value'=>$email]); ?>
		</div>
        <div class="form-group">
			<label>Password Sekarang</label>
			<?php echo $form->render('rpasswordlama'); ?>
		</div>
		<div class="form-group">
			<label>Password Baru</label>
			<p title="Sorry, but we don't do alot in security">Gunakan kombinasi huruf kecil, kapital dan angka minimal 8 karakter!</p>
			<?php echo $form->render('rpassword'); ?>
		</div>
		<div class="form-group">
			<label>Konfirmasi Password Baru</label>
			<p title="Please, don't fill it with 'Yes, it's my password' -_-">Masukkan kembali password yang sama!</p>
			<?php echo $form->render('rcpassword'); ?>
		</div>
		<div class="form-group">
			<?php echo $form->render('rsubmit',["value"=>"Simpan Perubahan","class"=>"btn btn-success"]); ?>
            <a href="<?=$this->url->getBaseUri().'user/profile'?>" class="btn btn-default btn-md">Kembali</a>
		</div>
		</form>
	</div>
<!-- adding bootstrap -->
<script src="<?=$this->url->getBaseUri()?>/js/bootstrap.js"></script>
<!-- adding jquery -->
<script src="<?=$this->url->getBaseUri()?>/js/jquery-3.3.1.js"></script>
<!-- adding external script -->
</body>
</html>