<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Riwayat &middot; booKesma</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Icon -->
	<link rel="icon" type="icon/image" href="<?=$this->url->getBaseUri()?>/img/jpgpng/favicon.png">
    <!-- adding bootstrap css-->
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/bootstrap.css" />
    <!-- adding bootstrap theme css-->
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/bootstrap-theme.css" />
    <!-- external page css -->
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/show.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body style="background-image: url('<?=$this->url->getBaseUri()?>/img/svg/bg_layer1.svg')">
<div class="topnav" id="top-nav" style="z-index: 99;">  
    <a class="home" href="<?=$this->url->getBaseUri()?>">
            <img src="<?=$this->url->getBaseUri()?>/img/svg/logo.svg" alt="booKesma">
        </a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'logout'?>">Keluar</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'user'?>">Riwayat</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseUri().'user/profile'?>">Hai, <?=$this->session->get('auth')['s_name'] ?>!</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'koleksi'?>">Koleksi</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'bagaimana'?>">Bagaimana</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'sumbang'?>">Sumbang</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'user/chat'?>">Chatting</a>
        <?php
            $role = $this->session->get('auth')['s_role'];
            if ($role==="admin") {
        ?>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'admin'?>">Admin</a>
        <?php
            }
        ?>
        <a href="javascript:void(0);" class="icon" onclick="navbar()">
            <img src="<?=$this->url->getBaseUri()?>/img/svg/hamburger-menu.svg" alt="menu">
        </a>
</div>
    <br><br><br><br>

    <div style="width:80%; height:500px; margin-left:10%; background-color: white; border: 3px solid lightblue; font-family:mp;">
        <h1 style="text-align: center;">RIWAYAT</h1>
        <hr>
        <div style="padding-left:5%; padding-right:5%;">
        <table class="table table-striped" style="padding-left:5%;">
    <thead>
      <tr>
        <th>Judul Buku</th>
        <th>Tanggal Peminjaman</th>
        <th>Tanggal Pengembalian</th>
        <th>Pengembalian</th>
      </tr>
    </thead>
    <tbody>
        <?php
        // var_dump($que);    
            if ($que) {
                foreach ($que as $q) {
        ?>
        <tr>
            <td><?=$q->judul_buku;?></td>
            <td><?=$q->tanggal_bertemu;?></td>
            <td><?=$q->tanggal_kembali;?></td>
            <?php
                // var_dump($q->status);
                //0=sdng dipesan u pinjam, 1=sdng pinjam, 2=cancel pinjam, 3=akan kembali, 4=tlh kembali
                if ($q->status == 1 || $q->status == 3) {
            ?>
                <td><a style="text-decoration:none;" href="<?=$this->url->getBaseUri()?>user/kembali/<?=$q->buku_id?>">Buat Tanggal Pengembalian</a></td>
            <?php
                }else if ($q->status == 4) {
            ?>
                <td><span class="glyphicon glyphicon-ok"></span></td>
            <?php
                }
            ?>
        </tr>
        <?php            
                }        
            }
        ?>
    </tbody>
  </table>
        </div>
    </div>
</body>
</html>