<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>booKesma &middot; Pinjam-Sumbang Buku Akademik Informatika ITS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Icon -->
	<link rel="icon" type="icon/image" href="img/jpgpng/favicon.png">
    <!-- adding bootstrap css-->
    <link rel="stylesheet" type="text/css" media="screen" href="css/bootstrap.css" />
    <!-- adding bootstrap theme css-->
    <link rel="stylesheet" type="text/css" media="screen" href="css/bootstrap-theme.css" />
    <!-- external page css -->
    <link rel="stylesheet" type="text/css" media="screen" href="css/show.css" />
</head>
<body style="background-image: url('img/svg/bg_layer1.svg')">
    <div class="topnav" id="top-nav" style="z-index: 99;">
        <a class="home" href="<?=$this->url->getBaseUri()?>">
            <img src="img/svg/logo.svg" alt="booKesma">
        </a>
        <a href="<?=$this->url->getBaseUri().'login'?>">Masuk</a>
        <a href="<?=$this->url->getBaseUri().'register'?>">Daftar</a>
        <a href="<?=$this->url->getBaseuri().'koleksi'?>">Koleksi</a>
        <a href="<?=$this->url->getBaseuri().'bagaimana'?>">Bagaimana</a>
        <a href="<?=$this->url->getBaseuri().'sumbang'?>">Sumbang</a>
        <a href="javascript:void(0);" class="icon" onclick="navbar()">
            <img src="img/svg/hamburger-menu.svg" alt="menu">
        </a>
    </div>
    <br><br><br><br>
</body>
</html>