<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Pengembalian &middot; booKesma</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Icon -->
	<link rel="icon" type="icon/image" href="<?=$this->url->getBaseUri()?>/img/jpgpng/favicon.png">
	<link rel="stylesheet" type="text/css" href="<?=$this->url->getBaseUri()?>/vendor/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="<?=$this->url->getBaseUri()?>/font/font-awesome-4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="<?=$this->url->getBaseUri()?>/font/Linearicons-Free-v1.0.0/icon-font.min.css">
	<!-- adding bootstrap css-->
	<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/bootstrap.css" />
    <!-- adding bootstrap theme css-->
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/bootstrap-theme.css" />
    <!-- external page css -->
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/show.css" />
	<link rel="stylesheet" type="text/css" href="<?=$this->url->getBaseUri()?>/css/util.css">
	<link rel="stylesheet" type="text/css" href="<?=$this->url->getBaseUri()?>/css/main.css">
</head>
<body style="background-image:url('<?=$this->url->getBaseUri()?>/img/svg/bg_layer1.svg')">
<div class="topnav" id="top-nav" style="z-index: 99;">  
    <a class="home" href="<?=$this->url->getBaseUri()?>">
            <img src="<?=$this->url->getBaseUri()?>/img/svg/logo.svg" alt="booKesma">
        </a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'logout'?>">Keluar</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'user'?>">Riwayat</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseUri().'user/profile'?>">Hai, <?=$this->session->get('auth')['s_name'] ?>!</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'koleksi'?>">Koleksi</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'bagaimana'?>">Bagaimana</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'sumbang'?>">Sumbang</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'user/chat'?>">Chatting</a>
        <?php
            $role = $this->session->get('auth')['s_role'];
            if ($role==="admin") {
        ?>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'admin'?>">Admin</a>
        <?php
            }
        ?>
        <a href="javascript:void(0);" class="icon" onclick="navbar()">
            <img src="<?=$this->url->getBaseUri()?>/img/svg/hamburger-menu.svg" alt="menu">
        </a>
</div>
	<div class="container-contact100" >
		<div class="wrap-contact100">
			<div class="contact100-form-title" style="background-image: url('<?=$this->url->getBaseUri()?>/img/2.jpg');">
				<span class="contact100-form-title-1">
					FORM PENGEMBALIAN
				</span>
			</div>
			<?=$this->tag->form([$this->url->getBaseUri().'user/kembali/'.$id_buku,'method'=>'post','class'=>'contact100-form validate-form']);?>
			<!-- <form class="contact100-form validate-form"> -->

				<div class="wrap-input100 validate-input" data-validate="Tanggal mengembalikan is required">
					<span class="label-input100">Tanggal Mengembalikan Buku:</span>
					<?php echo $form->render('tanggal'); ?>
					<!-- <input class="input100" type="date" name="tanggal_bertemu" placeholder="Masukkan Tanggal Kembali"> -->
					<span class="focus-input100"></span>
                </div>
                <div class="wrap-input100 validate-input" data-validate="No HP is required">
					<span class="label-input100">No HP:</span>
					<?php echo $form->render('nohp'); ?>
					<!-- <input class="input100" type="text" name="nomorhp" placeholder="Masukkan NO HP"> -->
					<span class="focus-input100"></span>
                </div>
                <div class="container-contact100-form-btn">
				<?php echo $form->render('submit'); ?>
					<!-- <button class="contact100-form-btn">
						<span>
							Submit
							<i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
						</span>
					</button> -->
				</div>
			<?= $this->tag->endForm()?>
			<!-- </form> -->
		</div>
	</div>

	<div id="dropDownSelect1"></div>

	<script src="<?=$this->url->getBaseUri()?>/vendor/jquery/jquery-3.2.1.min.js"></script>
	<script src="<?=$this->url->getBaseUri()?>/vendor/bootstrap/js/popper.js"></script>
	<script src="<?=$this->url->getBaseUri()?>/vendor/bootstrap/js/bootstrap.min.js"></script>
	<script src="<?=$this->url->getBaseUri()?>/js/main.js"></script>

</body>
</html>