<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Sumbang &middot; booKesma</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Icon -->
	<link rel="icon" type="icon/image" href="/bookesma.com/img/jpgpng/favicon.png">
	<link rel="stylesheet" type="text/css" href="/bookesma.com/vendor/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/bookesma.com/font/font-awesome-4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="/bookesma.com/font/Linearicons-Free-v1.0.0/icon-font.min.css">
	<!-- adding bootstrap css-->
	<link rel="stylesheet" type="text/css" media="screen" href="/bookesma.com/css/bootstrap.css" />
    <!-- adding bootstrap theme css-->
    <link rel="stylesheet" type="text/css" media="screen" href="/bookesma.com/css/bootstrap-theme.css" />
    <!-- external page css -->
    <link rel="stylesheet" type="text/css" media="screen" href="/bookesma.com/css/show.css" />
	<link rel="stylesheet" type="text/css" href="/bookesma.com/css/util.css">
	<link rel="stylesheet" type="text/css" href="/bookesma.com/css/main.css">
</head>
<body style="background-image:url('/bookesma.com/img/svg/bg_layer1.svg')">
<div class="topnav" id="top-nav" style="z-index: 99;">  
    <a class="home" href="<?=$this->url->getBaseUri()?>">
            <img src="/bookesma.com/img/svg/logo.svg" alt="booKesma">
        </a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'logout'?>">Keluar</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'user'?>">Riwayat</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseUri().'user/profile'?>">Hai, <?=$this->session->get('auth')['s_name'] ?>!</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'koleksi'?>">Koleksi</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'bagaimana'?>">Bagaimana</a>
        <a style="text-decoration: none;" href="<?=$this->url->getBaseuri().'sumbang'?>">Sumbang</a>
        <a href="javascript:void(0);" class="icon" onclick="navbar()">
            <img src="/bookesma.com/img/svg/hamburger-menu.svg" alt="menu">
        </a>
    </div>
	<div class="container-contact100" >
		<div class="wrap-contact100">
			<div class="contact100-form-title" style="background-image: url('/bookesma.com/img/2.jpg');">
				<span class="contact100-form-title-1">
					FORM RESERVASI
				</span>
			</div>

			<form class="contact100-form validate-form">

				<div class="wrap-input100 validate-input" data-validate="NRP is required">
					<span class="label-input100">Tanggal Kembali:</span>
					<input class="input100" type="date" name="tanggal_bertemu" placeholder="Masukkan Tanggal Kembali">
					<span class="focus-input100"></span>
                </div>
                <div class="wrap-input100 validate-input" data-validate="NRP is required">
					<span class="label-input100">No HP:</span>
					<input class="input100" type="text" name="nomorhp" placeholder="Masukkan NO HP">
					<span class="focus-input100"></span>
                </div>
                <div class="container-contact100-form-btn">
					<button class="contact100-form-btn">
						<span>
							Submit
							<i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
						</span>
					</button>
				</div>
			</form>
		</div>
	</div>

	<div id="dropDownSelect1"></div>

	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
	<script src="js/main.js"></script>

</body>
</html>
