<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Profil &middot; booKesma</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Icon -->
	<link rel="icon" type="icon/image" href="<?=$this->url->getBaseUri()?>/img/jpgpng/favicon.png">
    <!-- adding bootstrap css-->
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/bootstrap.css" />
    <!-- adding bootstrap theme css-->
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/bootstrap-theme.css" />
    <!-- external page css -->
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/show.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/profil.css" />
</head>
<body style="background-image: url('<?=$this->url->getBaseUri()?>/img/svg/bg_layer1.svg')">
    <div class="topnav" id="top-nav" style="z-index: 99;">
        <a class="home" href="<?=$this->url->getBaseUri()?>">
            <img src="<?=$this->url->getBaseUri()?>/img/svg/logo.svg" alt="booKesma">
        </a>
        <a href="<?=$this->url->getBaseuri().'logout'?>">Keluar</a>
        <a href="<?=$this->url->getBaseuri().'user'?>">Riwayat</a>
        <a href="<?=$this->url->getBaseUri().'user/profile'?>">Hai, <?=$this->session->get('auth')['s_name'] ?>!</a>
        <a href="<?=$this->url->getBaseuri().'user/koleksi'?>">Koleksi</a>
        <a href="<?=$this->url->getBaseuri().'user/bagaimana'?>">Bagaimana</a>
        <a href="<?=$this->url->getBaseuri().'sumbang'?>">Sumbang</a>
        <a href="javascript:void(0);" class="icon" onclick="navbar()">
            <img src="<?=$this->url->getBaseUri()?>/img/svg/hamburger-menu.svg" alt="menu">
        </a>
    </div>
    <div class="container" style="padding-top:8vw; height: 25vw;">
        <div id="konten" style="text-align: center;">
            <h3>Data Diri Anda</h3>
            <div class="form-group">
                <label>Username</label>
                <p><?=$nama?></p>
            </div>
            <div class="form-group">
                <label>NRP</label>
                <p><?=$nrp?></p>
            </div>
            <div class="form-group">
                <label>Email</label>
                <p><?=$email?></p>
            </div>
        </div>
        <div class="container" style="padding-top:2%;padding-left:44%;">
            <a href="<?=$this->url->getBaseUri().'user/edit-profile'?>" class="btn btn-info btn-md">Edit</a>
            <a href="<?=$this->url->getBaseUri().'home'?>" class="btn btn-default btn-md">Kembali</a>
        </div>
    </div>
<!-- adding bootstrap -->
<script src="<?=$this->url->getBaseUri()?>/js/bootstrap.js"></script>
<!-- adding jquery -->
<script src="<?=$this->url->getBaseUri()?>/js/jquery-3.3.1.js"></script>
<!-- adding external script -->
<script src="<?=$this->url->getBaseUri()?>/js/show.js"></script>
</body>
</html>