<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Semester-<?=$sem?> &middot; booKesma</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Icon -->
	<link rel="icon" type="icon/image" href="<?=$this->url->getBaseUri()?>/img/jpgpng/favicon.png">
    <!-- adding bootstrap css-->
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/bootstrap.css" />
    <!-- adding bootstrap theme css-->
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/bootstrap-theme.css" />
    <!-- external page css -->
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/show.css" />
    
	<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->url->getBaseUri()?>/css/time.css" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script type="text/javascript" src="<?=$this->url->getBaseUri()?>/js/js.js"></script>
</head>
<body>
<div class="topnav" id="top-nav" style="z-index: 99;">
        <a class="home" href="<?=$this->url->getBaseUri()?>">
            <img src="<?=$this->url->getBaseUri()?>/img/svg/logo.svg" alt="booKesma">
        </a>
        <a style="text-decoration:none;" href="<?=$this->url->getBaseuri().'logout'?>">Keluar</a>
        <a style="text-decoration:none;" href="<?=$this->url->getBaseuri().'user'?>">Riwayat</a>
        <a style="text-decoration:none;" href="<?=$this->url->getBaseUri().'user/profile'?>">Hai, <?=$this->session->get('auth')['s_name'] ?>!</a>
        <a style="text-decoration:none;" href="<?=$this->url->getBaseuri().'user/koleksi'?>">Koleksi</a>
        <a style="text-decoration:none;" href="<?=$this->url->getBaseuri().'bagaimana'?>">Bagaimana</a>
        <a style="text-decoration:none;" href="<?=$this->url->getBaseuri().'sumbang'?>">Sumbang</a>
        <a style="text-decoration:none;" href="javascript:void(0);" class="icon" onclick="navbar()">
            <img src="<?=$this->url->getBaseUri()?>/img/svg/hamburger-menu.svg" alt="menu">
        </a>
</div>
<br><br>
<!-- jumbotron -->
<div class="jumbotron jumbotron-fluid">
  <div class="container text-center">
    <h1>Koleksi Buku</h1>
    <p>Koleksi Buku Semester-<?=$sem?></p>
  </div>
  <form style="margin-left:40%;" class="navbar-form navbar-left" action="/action_page.php">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search" name="search">
        <div class="input-group-btn">
          <button class="btn btn-default" type="submit">
            <i class="glyphicon glyphicon-search"></i>
          </button>
        </div>
      </div>
    </form>
</div>
<!-- akhir jumbotron -->
<!-- buku -->
<section class="daftar" id="daftar" style="margin-left:5%;">
    <div class="container">
        <div class="row">
            <?php
                // var_dump($jumlah);
                if ($buku) {
                    foreach ($buku as $b) {
            ?>
                <div class="col-sm-4">
                    <a href="" class="thumbnail" data-toggle="modal" data-target="#modal<?=$b->id_buku;?>">
                        <img src="<?=$this->url->getBaseUri()?>/<?=$b->gambar;?>">
                    </a>
                </div>
                <!-- Modal content-->
                <div id="modal<?=$b->id_buku;?>" class="modal fade" role="dialog">
                    <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title"><?=$b->judul_buku;?></h4>
                        </div>
                        <div class="modal-body">
                            <p>Judul Buku : <br> <?=$b->judul_buku;?></p>
                            <p>Jumlah Halaman : <br> <?=$b->jumlah_halaman;?></p>
                            <p>Deskripsi Buku : <br> <?=$b->deskripsi_buku;?></p>
                            <?php
                                $flag = 0;
                                foreach ($que as $q) {
                                    if ($q->id_buku === $b->id_buku) {
                                        $flag = 1;
                                        break;
                                    }
                                }
                                if ($flag === 1) {
                                    $jumlah = (int)$b->tersedia - (int)$q->n;
                                }else{
                                    $jumlah = (int)$b->tersedia;
                                }
                            ?>
                            <p>Tersedia : <br> <?=$jumlah;?></p>
                        </div>
                    <div class="modal-footer">
                            <a href="<?=$this->url->getBaseuri()?>user/koleksi/semester/<?=$sem?>/<?=$b->id_buku;?>" class="btn btn-primary">Reservasi</a>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                    </div>
                    </div>
                </div>
            <?php
                    }
                }
            ?>
        </div>
    </div>
</section>
<br><br>
</body>
</html>