<!DOCTYPE html>
<html>
<head>
	<title>SEMESTER 1</title>
	<link rel="stylesheet" type="text/css" media="screen" href="css/style.css" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script type="text/javascript" src="js.js"></script>
</head>
<body>
<div id="header">
		<div id="atas">
			<div id="atasleft">
			<a href="#">
			<img src="img/download.png" alt="Youtube" style="width: 200px;height: 60px;"></a>
		</div>

		<div id="atasright">
        		
        <div id="navbar">
		<ul>
			<li><a id="" href="#">Kategori Buku</a></li>
  			<li><a id="" href="#">Bagaimana?</a></li>
		</ul>
	    </div>
			<a href=""><button style="width:auto;">Login</button></a>
            <a href=""><button style="width:auto;">Daftar</button></a>
		</div>
      <div class="input-group" style="width: 20%; float: right;">
        <input type="text" class="form-control"  id="myInput" placeholder="Search" name="search">
        <div class="input-group-btn">
          <button class="btn btn-default" type="submit">
            <i class="glyphicon glyphicon-search"></i>
          </button>
        </div>
      </div>
</div>
<div class="container" style="width: 8%; float: right;">                   
  <div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="menu1" data-toggle="dropdown">Sort
    <span class="caret"></span></button>
    <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
      <li role="presentation"><a role="menuitem" tabindex="-1" href="#">ID Buku</a></li>
      <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Judul Buku</a></li>
      <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Terakhir ditambah</a></li>
    </ul>
  </div>
</div>
<!-- jumbotron -->
<div class="jumbotron jumbotron-fluid">
  <div class="container text-center">
    <h1>Koleksi Buku</h1>
    <p>Koleksi buku semester 1</p>
  </div>
</div>
<!-- akhir jumbotron -->

<!-- buku -->
<section class="daftar" id="daftar">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h2>Daftar Buku</h2>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <a href="" class="thumbnail">
                    <img src="img/p1.jpg">
                </a>
            </div>
            <div class="col-sm-4">
                <a href="" class="thumbnail">
                    <img src="img/p2.jpg">
                </a>
            </div>
            <div class="col-sm-4">
                <a href="" class="thumbnail">
                    <img src="img/p3.jpg">
                </a>
            </div>
            <div class="col-sm-4">
                <a href="" class="thumbnail">
                    <img src="img/p4.jpg">
                </a>
            </div>
            <div class="col-sm-4">
                <a href="" class="thumbnail">
                    <img src="img/p5.jpg">
                </a>
            </div>
            <div class="col-sm-4">
                <a href="" class="thumbnail">
                    <img src="img/p6.jpg">
                </a>
            </div>
        </div>
    </div>
</section>
<!-- buku -->
</body>
</html>