<!DOCTYPE html>
<html>
<head>
	<title>KATEGORI BUKU</title>
	<link rel="stylesheet" type="text/css" media="screen" href="css/stylekategori.css" />
</head>
<body>
<div id="header">
		<div id="atas">
			<div id="atasleft">
			<a href="#">
			<img src="img/download.png" alt="Youtube" style="width: 200px;height: 60px;"></a>
		</div>

		<div id="atasright">
        		
        <div id="navbar">
		<ul>
			<li><a id="" href="#">Kategori Buku</a></li>
  			<li><a id="" href="#">Bagaimana?</a></li>
		</ul>
	    </div>
			<a href=""><button style="width:auto;">Login</button></a>
            <a href=""><button style="width:auto;">Daftar</button></a>
		</div>
</div>

<div id="isi">
	<h1>KATEGORI BUKU</h1>
	<div id="isi1">
		<div id="i2">
			<img src="img/isi2.jpg" style="width: 100%;">
        	<button>LIHAT</button>
		</div>
		<div id="i3">
			<img src="img/isi2.jpg" style="width: 100%;">
        	<button>LIHAT</button>
		</div>
		<div id="i2">
			<img src="img/isi2.jpg" style="width: 100%;">
        	<button>LIHAT</button>
		</div>
		<div id="i3">
			<img src="img/isi2.jpg" style="width: 100%;">
        	<button>LIHAT</button>
		</div>
		<br><br><br>
	</div>

	<div id="isi2">
		<div id="i3">
			<img src="img/isi2.jpg" style="width: 100%;">
        	<button>LIHAT</button>
		</div>
		<div id="i2">
			<img src="img/isi2.jpg" style="width: 100%;">
        	<button>LIHAT</button>
		</div>
		<div id="i3">
			<img src="img/isi2.jpg" style="width: 100%;">
        	<button>LIHAT</button>
		</div>
		<div id="i2">
			<img src="img/isi2.jpg" style="width: 100%;">
        	<button>LIHAT</button>
		</div>
	</div>
</div>
</body>
</html>