
<!DOCTYPE html>
<html>
<head>
	<title>Home</title>
	<link rel="stylesheet" type="text/css" href="css/styledaftar.css">
</head>
<body>

<div class="header">
	<h2>Home Page</h2>
</div>
<div class="content">
      <div class="error success" >
      	<h3>

      	</h3>
      </div>


    	<p>Welcome from Server <strong></strong></p>
      <p> <a href="homepage.php?logout='1'" style="color: red;">Logout</a> </p>
      <p><a href="homepage.php?ganti='1'" style="color: red;">Ganti Password</a></p>
      <p> <a href="index.php" style="color: red;">Kembali ke halaman awal</a> </p>
</div>
		
</body>
</html>